const Explordata=[
    {     
        pad:true,
        Img:"https://photos.shineinblue.com/wp-content/uploads/2022/05/333-5.jpg",
        catame:"food"
    },
    {
        pad:true,
        Img:"https://photos.shineinblue.com/wp-content/uploads/2022/05/333-5.jpg",
        catame:"cloth"
    },
    {
        pad:true,
        Img:"https://photos.shineinblue.com/wp-content/uploads/2022/05/333-5.jpg",
        catame:"anime"
    },
    {
        pad:true,
        Img:"https://photos.shineinblue.com/wp-content/uploads/2022/05/333-5.jpg",
        catame:"hunter"
    },
    {
        pad:true,
        Img:"https://photos.shineinblue.com/wp-content/uploads/2022/05/333-5.jpg",
        catame:"toys"
    },
    {
        pad:true,
        Img:"https://photos.shineinblue.com/wp-content/uploads/2022/05/333-5.jpg",
        catame:"flower"
    },
    {
        pad:true,
        Img:"https://photos.shineinblue.com/wp-content/uploads/2022/05/333-5.jpg",
        catame:"flower"
    }
]
export default Explordata